version: "3.3"

services:
  ubuntu:
    build:
      context: ./otserver
    container_name: OTServer
    stdin_open: true
    tty: true
    ports:
      - "7171:7171"
      - "7172:7172"
    volumes:
      - ./otserver/datapack:/srv
    depends_on:
      - db

  web:
    build:
      context: ./otsite
    container_name: OTSite
    ports:
      - "8080:8080" 
    environment:
      - NODE_ENV=production
    command: npm start
    volumes:
      - ./otsite/public:/var/www/html
      - ./otsite:/app
    depends_on:
      - db
    networks:
      - app-network
      
  db:
    image: mysql:5.7
    container_name: OTDataBase
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: otserv
      MYSQL_PASSWORD: 1234
    volumes:
      - ./otserver/schema:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network

  dbAdminPainel:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: OTDbAdmin
    restart: always
    ports:
      - 1010:80
    links:
      - db
    environment:
      PMA_ARBITRARY: 1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
